services:
  - type: web
    name: paintafrica-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: SUPABASE_URL
        value: https://aftutesaohrfdnmeuyq.supabase.co
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: CORS_ORIGIN
        value: http://localhost:5173,https://paintafrica.vercel.app
