services:
  - type: web
    name: paintafrica-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: https://aftutevsaohrfdnmeuyq.supabase.co/rest/v1/
        sync: false
      - key: sb_publishable_eplMkNxq8YSCvpdWXup33Q_7p8rHeK6
        sync: false
      - key: CORS_ORIGIN
        value: http://localhost:5173,https://your-frontend-deployed-url.vercel.app
